#!/bin/bash


readarray -t lines < computerlist.txt

declare -A names

while IFS==" " read -r compname username
do
    names[$compname]=$username
done < fullcomputerlist.txt

for i in "${!names[@]}"
do
    COMMAND1="sudo -i -u ${names[$i]} gnome-terminal --geometry=120x40 -- env TEACHSCREEN=/home/murry/screenrc screen;"
    nohup ssh -t $i "$COMMAND1" >& /dev/null &
done
